FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

ENV SNOWFLAKE_USER=XXXXXXXXXXXXXXXX
ENV SNOWFLAKE_PASSWORD=XXXXXXXXXXXXXXXX
ENV SNOWFLAKE_ACCOUNT=XXXXXXXXXXXXXXXX
ENV SNOWFLAKE_DATABASE=XXXXXXXXXXXXXXXX
ENV SNOWFLAKE_SCHEMA=XXXXXXXXXXXXXXXX

CMD ["dagster", "dev", "-f", "dagster_project/repository.py", "--host", "0.0.0.0"]

